

import MainLayout from "@/components/MainLayout";
import "./globals.css";
import { Provider } from "react-redux";



export const metadata = {
  title: "This is Tailwind",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <MainLayout>
    {children}
      
        </MainLayout>
      </body>
    </html>
  );
}
